name: test
on: [push]
jobs:
  test-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.24.x'
          channel: 'dev'
      - run: flutter pub get
      - run: dart analyze --fatal-infos .
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter test
